package com.dSystems.demo.Payload;

/**
 * THE LOGIN SUCCESS RECEIPT / RESPONSE PAYLOAD.
 * 
 * Think of this class as the "admission ticket package" sent back to the user after a successful login.
 * It contains the username and a cryptographically signed key (token) that acts as their entry pass.
 */
public class AuthResponse {

    // The security ticket (JWT token) generated by the server.
    // The user's web browser will save this token and attach it to all future requests
    // to prove who they are without having to type their username and password again.
    private final String token;
    
    // The confirmed username of the logged-in user.
    private final String username;

    /**
     * Constructor - Creates the success receipt with the ticket and username.
     */
    public AuthResponse(String token, String username) {
        this.token = token;
        this.username = username;
    }

    // --- GETTERS ---
    // Methods to read the response data (these fields are "final" / read-only once created).

    public String getToken() {
        return token;
    }

    public String getUsername() {
        return username;
    }
}
