#Chunk upload metadata
#Fri Mar 20 12:49:37 IST 2026
chunk.0=/home/madhan/Desktop/demo(1)/demo/temp/file_1/chunk-0.part
chunk.1=/home/madhan/Desktop/demo(1)/demo/temp/file_1/chunk-1.part
chunk.2=/home/madhan/Desktop/demo(1)/demo/temp/file_1/chunk-2.part
fileId=file_1
originalFileName=chunk_ac
tempDirectory=/home/madhan/Desktop/demo(1)/demo/temp/file_1
totalChunks=3
