
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:user_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  jwt:
    secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
    expiration-seconds: 18000
  tempDir: ${APP_TEMP_DIR:temp/}
  uploadDir: ${APP_UPLOAD_DIR:uploads/}
  maxChunksPerFile: ${APP_MAX_CHUNKS:10}
  replicationFactor: ${APP_REPLICATION_FACTOR:3}
  role: ${APP_ROLE:COORDINATOR}
  coordinatorUrl: ${APP_COORDINATOR_URL:http://localhost:9000}
  nodeId: ${APP_NODE_ID:coordinator}
  host: ${APP_HOST:localhost}
  port: ${APP_PORT:9000}
server:
  port: ${PORT:9000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
