version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"

  coordinator:
    build: .
    ports:
      - "9000:9000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 9000
      APP_ROLE: COORDINATOR
      APP_NODE_ID: coordinator
      APP_HOST: coordinator
      APP_PORT: 9000
      APP_REPLICATION_FACTOR: 2
    depends_on:
      - postgres

  node-1:
    build: .
    ports:
      - "9001:9001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 9001
      APP_ROLE: NODE
      APP_NODE_ID: node-1
      APP_HOST: node-1
      APP_PORT: 9001
      APP_COORDINATOR_URL: http://coordinator:9000
      APP_TEMP_DIR: temp/node-1/
      APP_REPLICATION_FACTOR: 2
    depends_on:
      - coordinator

  node-2:
    build: .
    ports:
      - "9002:9002"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 9002
      APP_ROLE: NODE
      APP_NODE_ID: node-2
      APP_HOST: node-2
      APP_PORT: 9002
      APP_COORDINATOR_URL: http://coordinator:9000
      APP_TEMP_DIR: temp/node-2/
      APP_REPLICATION_FACTOR: 2
    depends_on:
      - coordinator

  node-3:
    build: .
    ports:
      - "9003:9003"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 9003
      APP_ROLE: NODE
      APP_NODE_ID: node-3
      APP_HOST: node-3
      APP_PORT: 9003
      APP_COORDINATOR_URL: http://coordinator:9000
      APP_TEMP_DIR: temp/node-3/
      APP_REPLICATION_FACTOR: 2
    depends_on:
      - coordinator
